trigger:
  batch: true
  branches:
    include:
    - master
    - releases/*
    - features/*
  paths:
    exclude: [ 'README.md' ]

jobs:
- job: macos
  pool: {vmImage: 'macOS-10.15'}
  steps:
    - script: |
        python3 -m pip install --upgrade pip
        python3 -m pip install wheel
        python3 setup.py build bdist_wheel --plat-name macosx_10_5_x86_64 --dist-dir ../wheelhouse
      workingDirectory: electrumsv-sdk/
    - task: PublishBuildArtifacts@1
      inputs:
        artifactName: 'MacOS'
        pathtoPublish: 'wheelhouse'

- job: windows
  pool: {vmImage: 'windows-latest'}
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: 3.7
    - script: |
        py -3 -m pip install --upgrade pip
        py -3 -m pip install wheel
        py -3 .\setup.py build bdist_wheel --plat-name win-amd64 --dist-dir ../wheelhouse
      workingDirectory: electrumsv-sdk/
    - task: PublishBuildArtifacts@1
      inputs:
        artifactName: 'Windows'
        pathtoPublish: 'wheelhouse'

- job: linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: 3.7
    - bash: |
        python3 -m pip install --upgrade pip
        python3 -m pip install wheel
        python3 setup.py build bdist_wheel --plat-name manylinux2014_x86_64 --dist-dir ../wheelhouse
      workingDirectory: electrumsv-sdk/
    - task: PublishBuildArtifacts@1
      inputs:
        artifactName: 'Linux'
        pathtoPublish: 'wheelhouse'
